# Generated by Django 5.2.10 on 2026-01-10 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0002_rename_user_myuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salon',
            name='salon_id',
        ),
    ]
