# Generated by Django 5.2.10 on 2026-01-10 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_remove_salon_salon_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='username_text',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
